rootProject.name = "tiltakspenger-libs"

include(
    "person-dtos",
    "arenatiltak-dtos",
    "tiltak-dtos",
    "soknad-dtos",
    "periodisering",
    "personklient:personklient-infrastruktur",
    "personklient:personklient-domene",
    "jobber",
    "common",
    "test-common",
    "persistering:persistering-infrastruktur",
    "persistering:persistering-domene",
    "persistering:persistering-test-common",
    "auth-test-core",
    "httpklient",
    "json",
    "ktor-common",
    "ktor-test-common",
    "logging",
    "meldekort-dtos",
    "meldekort",
    "kafka",
    "kafka-test",
    "texas",
    "satser"
)
