package no.nav.tiltakspenger.libs.arena.tiltak

import java.time.LocalDate

data class ArenaTiltaksaktivitetResponsDTO(
    val tiltaksaktiviteter: List<TiltaksaktivitetDTO>? = null,
    val feil: FeilmeldingDTO? = null,
) {

    enum class FeilmeldingDTO(val melding: String) {
        UkjentFeil("Ukjent feil"),
    }

    data class TiltaksaktivitetDTO(
        val tiltakType: TiltakType,
        val aktivitetId: String,
        val tiltakLokaltNavn: String?,
        val arrangoer: String?,
        val bedriftsnummer: String?,
        val deltakelsePeriode: DeltakelsesPeriodeDTO?,
        val deltakelseProsent: Float?,
        val deltakerStatusType: DeltakerStatusType,
        val statusSistEndret: LocalDate?,
        val begrunnelseInnsoeking: String?,
        val antallDagerPerUke: Float?,
    )

    data class DeltakelsesPeriodeDTO(
        val fom: LocalDate?,
        val tom: LocalDate?,
    )

    enum class Tiltaksgruppe(val navn: String) {
        AFT("Arbeidsforberedende trening"),
        AMB("Tiltak i arbeidsmarkedsbedrift"),
        ARBPRAKS("Arbeidspraksis"),
        ARBRREHAB("Arbeidsrettet rehabilitering"),
        ARBTREN("Arbeidstrening"),
        AVKLARING("Avklaring"),
        BEHPSSAM("Behandling - lettere psykiske/sammensatte lidelser"),
        ETAB("Egenetablering"),
        FORSOK("Forsøk"),
        LONNTILS("Lønnstilskudd"),
        OPPFOLG("Oppfølging"),
        OPPL("Opplæring"),
        TILRETTE("Tilrettelegging"),
        UTFAS("Tiltak under utfasing"),
        VARIGASV("Varig tilrettelagt arbeid"),
        JOBBSKAP("Jobbskapingsprosjekter"),
        BIO("Bedriftsintern opplæring (BIO)"),
        BISTAND("Arbeid med Bistand (AB)"),
        INST_S("Nye plasser institusjonelle tiltak"),
        MIDSYSS("Midlertidig sysselsetting"),
    }

    enum class TiltakType(val navn: String, val tiltaksgruppe: Tiltaksgruppe, val rettPåTiltakspenger: Boolean) {
        // gir rett
        ARBTREN("Arbeidstrening", Tiltaksgruppe.ARBTREN, true),
        GRUPPEAMO("Gruppe AMO", Tiltaksgruppe.OPPL, true),
        ENKELAMO("Enkeltplass AMO", Tiltaksgruppe.OPPL, true),
        GRUFAGYRKE("Gruppe Fag- og yrkesopplæring VGS og høyere yrkesfaglig utdanning", Tiltaksgruppe.OPPL, true),
        ENKFAGYRKE("Enkeltplass Fag- og yrkesopplæring VGS og høyere yrkesfaglig utdanning", Tiltaksgruppe.OPPL, true),
        HOYEREUTD("Høyere utdanning", Tiltaksgruppe.OPPL, true),
        ARBFORB("Arbeidsforberedende trening (AFT)", Tiltaksgruppe.AFT, true),
        UTVAOONAV("Arbeid med støtte", Tiltaksgruppe.FORSOK, true),
        FORSAMOGRU("Forsøk AMO gruppe", Tiltaksgruppe.FORSOK, true),
        FORSAMOENK("Forsøk AMO enkeltplass", Tiltaksgruppe.FORSOK, true),
        FORSFAGGRU("Forsøk fag- og yrkesopplæring gruppe", Tiltaksgruppe.FORSOK, true),
        FORSFAGENK("Forsøk fag- og yrkesopplæring enkeltplass", Tiltaksgruppe.FORSOK, true),
        FORSHOYUTD("Forsøk høyere utdanning", Tiltaksgruppe.FORSOK, true),
        FORSOPPLEV("Forsøk opplæringstiltak av lengre varighet", Tiltaksgruppe.FORSOK, true),
        AVKLARAG("Avklaring", Tiltaksgruppe.AVKLARING, true),
        ARBRRHDAG("Arbeidsrettet rehabilitering (dag)", Tiltaksgruppe.ARBRREHAB, true),
        JOBBK("Jobbklubb", Tiltaksgruppe.OPPFOLG, true),
        INDOPPFAG("Oppfølging", Tiltaksgruppe.OPPFOLG, true),
        INDJOBSTOT("Individuell jobbstøtte (IPS)", Tiltaksgruppe.OPPFOLG, true),
        DIGIOPPARB("Digitalt oppfølgingstiltak for arbeidsledige (jobbklubb)", Tiltaksgruppe.OPPFOLG, true),
        UTVOPPFOPL("Utvidet oppfølging i opplæring", Tiltaksgruppe.OPPFOLG, true),
        IPSUNG("Individuell karrierestøtte (IPS Ung)", Tiltaksgruppe.OPPFOLG, true),

        // gir ikke rett
        REFINO("Resultatbasert finansiering av oppfølging", Tiltaksgruppe.FORSOK, false),
        MIDLONTIL("Midlertidig lønnstilskudd", Tiltaksgruppe.LONNTILS, false),
        VARLONTIL("Varig lønnstilskudd", Tiltaksgruppe.LONNTILS, false),
        TILSJOBB("Tilskudd til sommerjobb", Tiltaksgruppe.LONNTILS, false),
        ETAB("Egenetablering", Tiltaksgruppe.ETAB, false),
        VASV("Varig tilrettelagt arbeid i skjermet virksomhet", Tiltaksgruppe.VARIGASV, false),
        VATIAROR("Varig tilrettelagt arbeid i ordinær virksomhet", Tiltaksgruppe.VARIGASV, false),
        FUNKSJASS("Funksjonsassistanse", Tiltaksgruppe.TILRETTE, false),
        INKLUTILS("Inkluderingstilskudd", Tiltaksgruppe.TILRETTE, false),
        EKSPEBIST("Ekspertbistand", Tiltaksgruppe.TILRETTE, false),
        MENTOR("Mentor", Tiltaksgruppe.OPPFOLG, false),

        // utfases
        AMBF1("AMB Avklaring (fase 1)", Tiltaksgruppe.UTFAS, false),
        KURS("Andre kurs", Tiltaksgruppe.UTFAS, false),
        ANNUTDANN("Annen utdanning", Tiltaksgruppe.UTFAS, false),
        ABOPPF("Arbeid med bistand A oppfølging", Tiltaksgruppe.UTFAS, false),
        ABUOPPF("Arbeid med bistand A utvidet oppfølging", Tiltaksgruppe.UTFAS, false),
        ABIST("Arbeid med Bistand (AB)", Tiltaksgruppe.UTFAS, false),
        ABTBOPPF("Arbeid med bistand B", Tiltaksgruppe.UTFAS, false),
        AMO("Arbeidsmarkedsopplæring (AMO)", Tiltaksgruppe.UTFAS, false),
        AMOE("Arbeidsmarkedsopplæring (AMO) enkeltplass", Tiltaksgruppe.UTFAS, false),
        AMOB("Arbeidsmarkedsopplæring (AMO) i bedrift", Tiltaksgruppe.UTFAS, false),
        AMOY("Arbeidsmarkedsopplæring (AMO) yrkeshemmede", Tiltaksgruppe.UTFAS, false),
        PRAKSORD("Arbeidspraksis i ordinær virksomhet", Tiltaksgruppe.UTFAS, false),
        PRAKSKJERM("Arbeidspraksis i skjermet virksomhet", Tiltaksgruppe.UTFAS, false),
        ARBRRHBAG("Arbeidsrettet rehabilitering", Tiltaksgruppe.UTFAS, false),
        ARBRRHBSM("Arbeidsrettet rehabilitering - sykmeldt arbeidstaker", Tiltaksgruppe.UTFAS, false),
        ARBRDAGSM("Arbeidsrettet rehabilitering (dag) - sykmeldt arbeidstaker", Tiltaksgruppe.UTFAS, false),
        ARBRRDOGN("Arbeidsrettet rehabilitering (døgn)", Tiltaksgruppe.UTFAS, false),
        ARBDOGNSM("Arbeidsrettet rehabilitering (døgn) - sykmeldt arbeidstaker", Tiltaksgruppe.UTFAS, false),
        ASV("Arbeidssamvirke (ASV)", Tiltaksgruppe.UTFAS, false),
        ATG("Arbeidstreningsgrupper", Tiltaksgruppe.UTFAS, false),
        AVKLARUS("Avklaring", Tiltaksgruppe.UTFAS, false),
        AVKLARSP("Avklaring - sykmeldt arbeidstaker", Tiltaksgruppe.UTFAS, false),
        AVKLARKV("Avklaring av kortere varighet", Tiltaksgruppe.UTFAS, false),
        AVKLARSV("Avklaring i skjermet virksomhet", Tiltaksgruppe.UTFAS, false),
        BIA("Bedriftsintern attføring", Tiltaksgruppe.UTFAS, false),
        BREVKURS("Brevkurs", Tiltaksgruppe.UTFAS, false),
        DIVTILT("Diverse tiltak", Tiltaksgruppe.UTFAS, false),
        FLEKSJOBB("Fleksibel jobb - lønnstilskudd av lengre varighet", Tiltaksgruppe.UTFAS, false),
        TILRTILSK("Forebyggings- og tilretteleggingstilskudd IA virksomheter og BHT-honorar", Tiltaksgruppe.UTFAS, false),
        KAT("Formidlingstjenester", Tiltaksgruppe.UTFAS, false),
        VALS("Formidlingstjenester - Ventelønn", Tiltaksgruppe.UTFAS, false),
        GRUNNSKOLE("Grunnskole", Tiltaksgruppe.UTFAS, false),
        HOYSKOLE("Høyskole/Universitet", Tiltaksgruppe.UTFAS, false),
        INDOPPFOLG("Individuelt oppfølgingstiltak", Tiltaksgruppe.UTFAS, false),
        ITGRTILS("Integreringstilskudd", Tiltaksgruppe.UTFAS, false),
        JOBBKLUBB("Intern jobbklubb", Tiltaksgruppe.UTFAS, false),
        JOBBFOKUS("Jobbfokus/Utvidet formidlingsbistand", Tiltaksgruppe.UTFAS, false),
        JOBBBONUS("Jobbklubb med bonusordning", Tiltaksgruppe.UTFAS, false),
        JOBBSKAP("Jobbskapingsprosjekter", Tiltaksgruppe.UTFAS, false),
        AMBF2("Kvalifisering i arbeidsmarkedsbedrift", Tiltaksgruppe.UTFAS, false),
        STATLAERL("Lærlinger i statlige etater", Tiltaksgruppe.UTFAS, false),
        LONNTILS("Lønnstilskudd", Tiltaksgruppe.UTFAS, false),
        REAKTUFOR("Lønnstilskudd - reaktivisering av uførepensjonister", Tiltaksgruppe.UTFAS, false),
        LONNTILL("Lønnstilskudd av lengre varighet", Tiltaksgruppe.UTFAS, false),
        NETTAMO("Nettbasert arbeidsmarkedsopplæring (AMO)", Tiltaksgruppe.UTFAS, false),
        NETTKURS("Nettkurs", Tiltaksgruppe.UTFAS, false),
        INST_S("Nye plasser institusjonelle tiltak", Tiltaksgruppe.UTFAS, false),
        INDOPPFSP("Oppfølging - sykmeldt arbeidstaker", Tiltaksgruppe.UTFAS, false),
        SYSSLANG("Sysselsettingstiltak for langtidsledige", Tiltaksgruppe.UTFAS, false),
        YHEMMOFF("Sysselsettingstiltak for yrkeshemmede", Tiltaksgruppe.UTFAS, false),
        SYSSOFF("Sysselsettingstiltak i offentlig sektor for yrkeshemmede", Tiltaksgruppe.UTFAS, false),
        LONNTIL("Tidsbegrenset lønnstilskudd", Tiltaksgruppe.UTFAS, false),
        TIDSUBLONN("Tidsubestemt lønnstilskudd", Tiltaksgruppe.UTFAS, false),
        AMBF3("Tilrettelagt arbeid i arbeidsmarkedsbedrift", Tiltaksgruppe.UTFAS, false),
        TILRETTEL("Tilrettelegging for arbeidstaker", Tiltaksgruppe.UTFAS, false),
        TILPERBED("Tilretteleggingstilskudd for arbeidssøker", Tiltaksgruppe.UTFAS, false),
        PV("Produksjonsverksted (PV)", Tiltaksgruppe.UTFAS, false),
        SPA("Spa prosjekter", Tiltaksgruppe.UTFAS, false),
        UFØREPENLØ("Uførepensjon som lønnstilskudd", Tiltaksgruppe.UTFAS, false),
        UTDYRK("Utdanning", Tiltaksgruppe.UTFAS, false),
        UTDPERMVIK("Utdanningspermisjoner", Tiltaksgruppe.UTFAS, false),
        VIKARBLED("Utdanningsvikariater", Tiltaksgruppe.UTFAS, false),
        UTBHLETTPS("Utredning/behandling lettere psykiske lidelser", Tiltaksgruppe.UTFAS, false),
        UTBHPSLD("Utredning/behandling lettere psykiske og sammensatte lidelser", Tiltaksgruppe.UTFAS, false),
        UTBHSAMLI("Utredning/behandling sammensatte lidelser", Tiltaksgruppe.UTFAS, false),
        VV("Varig vernet arbeid (VVA)", Tiltaksgruppe.UTFAS, false),
        VIDRSKOLE("Videregående skole", Tiltaksgruppe.UTFAS, false),
        OPPLT2AAR("2-årig opplæringstiltak", Tiltaksgruppe.UTFAS, false),

        // rariteter
        LONNTILAAP("Arbeidsavklaringspenger som lønnstilskudd", Tiltaksgruppe.FORSOK, false),
        BIO("Bedriftsintern opplæring (BIO)", Tiltaksgruppe.BIO, false),
        TESTING("Lenes testtiltak", Tiltaksgruppe.OPPFOLG, false),
        NYTEST("Nytt testtiltak", Tiltaksgruppe.ARBTREN, false),
        INDOPPRF("Resultatbasert finansiering av formidlingsbistand", Tiltaksgruppe.FORSOK, true),
        SUPPEMP("Supported Employment", Tiltaksgruppe.FORSOK, true),
    }

    enum class DeltakerStatusType(val navn: String) {
        AKTUELL("Aktuell"),
        AVSLAG("Fått avslag"),
        DELAVB("Deltakelse avbrutt"),
        FULLF("Fullført"),
        GJENN("Gjennomføres"),
        GJENN_AVB("Gjennomføring avbrutt"),
        GJENN_AVL("Gjennomføring avlyst"),
        IKKAKTUELL("Ikke aktuell"),
        IKKEM("Ikke møtt"),
        INFOMOETE("Informasjonsmøte"),
        JATAKK("Takket ja til tilbud"),
        NEITAKK("Takket nei til tilbud"),
        TILBUD("Godkjent tiltaksplass"),
        VENTELISTE("Venteliste"),
        FEILREG("Feilregistrert"),
    }
}
