package no.nav.tiltakspenger.libs.tiltak

/**
 * https://confluence.adeo.no/pages/viewpage.action?pageId=653427539
 */
enum class TiltakstypeSomGirRett {
    /** ARBEIDSFORBEREDENDE_TRENING i Komet per 2024-08-14  */
    ARBEIDSFORBEREDENDE_TRENING,

    ARBEIDSMARKEDSOPPLAERING,

    /** ARBEIDSRETTET_REHABILITERING i Komet per 2024-08-14  */
    ARBEIDSRETTET_REHABILITERING,
    ARBEIDSTRENING,

    /** AVKLARING i Komet per 2024-08-14  */
    AVKLARING,

    /** DIGITALT_OPPFOLGINGSTILTAK i Komet per 2024-08-14 */
    DIGITAL_JOBBKLUBB,
    ENKELTPLASS_AMO,
    ENKELTPLASS_VGS_OG_HØYERE_YRKESFAG,

    FAG_OG_YRKESOPPLAERING,

    FORSØK_OPPLÆRING_LENGRE_VARIGHET,

    /** GRUPPE_ARBEIDSMARKEDSOPPLAERING i Komet per 2024-08-14 */
    GRUPPE_AMO,

    /** GRUPPE_FAG_OG_YRKESOPPLAERING i Komet per 2024-08-14 */
    GRUPPE_VGS_OG_HØYERE_YRKESFAG,
    HØYERE_UTDANNING,
    HOYERE_YRKESFAGLIG_UTDANNING,
    INDIVIDUELL_JOBBSTØTTE,
    INDIVIDUELL_KARRIERESTØTTE_UNG,

    /** JOBBKLUBB i Komet per 2024-08-14 */
    JOBBKLUBB,

    /** OPPFOLGING i Komet per 2024-08-14 */
    OPPFØLGING,
    NORSKOPPLAERING_GRUNNLEGGENDE_FERDIGHETER_FOV,
    STUDIESPESIALISERING,
    UTVIDET_OPPFØLGING_I_NAV,
    UTVIDET_OPPFØLGING_I_OPPLÆRING,
}
