on: [ pull_request ]
name: Pull Request

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
   test:
    runs-on: ubuntu-latest
    name: Run Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v3
        with:
          arguments: test --continue --no-daemon --configuration-cache

      - uses: dorny/test-reporter@v1.9.0
        if: success() || failure()
        with:
          name: Test Result
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}
