on: [ pull_request ]
name: Pull Request

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
   test:
    runs-on: ubuntu-latest
    name: Run Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - shell: bash
        run: ./gradlew build
