name: Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          check-latest: true
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: test --continue --no-daemon --configuration-cache
      - uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: tests
          path: "*/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # include git tags

      - uses: paulhatch/semantic-version@v5.4.0
        id: tag
        with:
          bump_each_commit: true
          tag_prefix: ""

      - id: notes
        run: |
          randomDelimiter=${RANDOM}
          text="$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s")"
          echo 'CHANGELOG<<$randomDelimiter' >> $GITHUB_OUTPUT
          echo $text >> $GITHUB_OUTPUT
          echo '$randomDelimiter' >> $GITHUB_OUTPUT

      - uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          release_name: ${{ steps.tag.outputs.version }}
          body: |
            Changes in this Release
            ${{ steps.notes.outputs.CHANGELOG }}

      - uses: gradle/gradle-build-action@v3
        with:
          arguments: -Pversion=${{ steps.tag.outputs.version }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
