name: Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: test, build and release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # include git tags
      - uses: paulhatch/semantic-version@v5.4.0
        id: tag
        with:
          bump_each_commit: true
          tag_prefix: ""
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - name: Test, build and publish
        run: ./gradlew -Pversion=${{ steps.tag.outputs.version }} build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.version }}
          tag_name: ${{ steps.tag.outputs.version }}
          prerelease: false
#  release:
#    runs-on: ubuntu-latest
#    needs: build
#    permissions:
#      contents: write
#      packages: write
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0 # include git tags
#
#      - uses: paulhatch/semantic-version@v5.4.0
#        id: tag
#        with:
#          bump_each_commit: true
#          tag_prefix: ""
#
#      - id: notes
#        run: |
#          randomDelimiter=${RANDOM}
#          text="$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s")"
#          echo 'CHANGELOG<<$randomDelimiter' >> $GITHUB_OUTPUT
#          echo $text >> $GITHUB_OUTPUT
#          echo '$randomDelimiter' >> $GITHUB_OUTPUT
#
#      - uses: actions/create-release@v1.1.4
#        id: create_release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.tag.outputs.version }}
#          release_name: ${{ steps.tag.outputs.version }}
#          body: |
#            Changes in this Release
#            ${{ steps.notes.outputs.CHANGELOG }}
#      - uses: actions/setup-java@v4
#        with:
#          java-version: 21
#          distribution: 'temurin'
#          check-latest: true
#      - uses: gradle/gradle-build-action@v3
#        with:
#          arguments: -Pversion=${{ steps.tag.outputs.version }} publish
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
